heat_template_version: 2015-04-30
description: Installs MongoDB Client

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  server_list:
    type: comma_delimited_list
    description: List of server IDs

  server_names:
    type: comma_delimited_list
    description: List of server names

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

resources:

  # SOFTWARE CONFIGS

  install_repo:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/1_install-repo.sh }
      inputs:
        - name: http_proxy
        - name: https_proxy
        - name: noproxy

  install_mongo_client:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/install-mongo-client.sh }
      inputs:
        - name: http_proxy
        - name: https_proxy
        - name: noproxy

  # SOFTWARE DEPLOYMENTS

  deploy_install_repo:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: install_repo }
      servers: { get_param: server_map }
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: http_proxy }
        no_proxy: { get_param: no_proxy }

  deploy_install_mongo_client:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: install_mongo_client }
      servers: { get_param: server_map }
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: http_proxy }
        no_proxy: { get_param: no_proxy }
    depends_on:
      - deploy_install_repo
  
outputs:
